version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Run Shellcheck
          command: |
            make shellcheck

      - run:
          name: Create SD image
          no_output_timeout: 45m
          command: |
            VERSION=${CIRCLE_TAG} make sd-image-rdbox

      - run:
          name: Prepare artifacts
          command: |
            mkdir -p output
            cp hypriotos*zip* output/

      - store_artifacts:
          path: /home/circleci/project/output

      - deploy:
          name: Deploy
          command: |
            if [ "$CIRCLE_TAG" != "" ]; then
              curl -sSL https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz -o ghr.tar.gz
              tar xzf ghr.tar.gz
              if [[ $CIRCLE_TAG = *"rc"* ]]; then
                pre=-prerelease
              fi
              ./ghr_v0.12.0_linux_amd64/ghr $pre -u rdbox-intec -r rdbox $(echo $CIRCLE_TAG | cut -f 4 -d "-" | tr -d "\n") output/
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
